import TencentCallsUikitPlugin from './src/main/ets/components/plugin/TencentCallsUikitPlugin';

export default TencentCallsUikitPlugin;

export { TUICallKit } from './src/main/ets/TUICallKit';
export {
  NOTIFICATION_CALL_ACTION_ACCEPT,
  NOTIFICATION_CALL_ACTION_KEY,
  NOTIFICATION_CALL_ACTION_REJECT,
  NOTIFICATION_CALL_ID_KEY,
} from './src/main/ets/feature/IncomingNotificationFeature';
export { CallMediaType, CallParams, CloudRecordPolicy } from '@tencentcloud/atomicxcore';
